"""Initial migration.

Revision ID: 075a65b18a2c
Revises: fa6976b9a964
Create Date: 2024-08-14 11:13:23.670922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075a65b18a2c'
down_revision = 'fa6976b9a964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('vendor_supplier', sa.VARCHAR(length=100), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('receipt_document', sa.VARCHAR(length=50), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    # ### end Alembic commands ###
